export const orderConstant={
    GET_ALL_ORDER_REQ:"GET_ALL_ORDER_REQ",
    GET_ALL_ORDER_SUC:"GET_ALL_ORDER_SUC",
    GET_ALL_ORDER_FAILURE:"GET_ALL_ORDER_FAILURE",
    NEW_ORDER_REQ:"NEW_ORDER_REQ",
    NEW_ORDER_SUC:"NEW_ORDER_SUC",
    NEW_ORDER_FAILURE:"NEW_ORDER_FAILURE",
    NEW_ORDER_PDF_REQ:"NEW_ORDER_PDF_REQ",
    NEW_ORDER_PDF_SUC:"NEW_ORDER_PDF_SUC",
    NEW_ORDER_PDF_FAILURE:"NEW_ORDER_PDF_FAILURE",
}

export const userConstant={
    USER_LOGIN_REQ:"USER_LOGIN_REQ",
    USER_LOGIN_SUC:"USER_LOGIN_SUC",
    USER_LOGIN_FAILURE:"USER_LOGIN_FAILURE",
    USER_REGISTER_REQ:"USER_REGISTER_REQ",
    USER_REGISTER_SUC:"USER_REGISTER_SUC",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE",
    USER_LOGOUT_REQ:"USER_LOGOUT_REQ",
    USER_LOGOUT_SUC:"USER_LOGOUT_SUC",
    USER_LOGOUT_FAILURE:"USER_LOGOUT_FAILURE"
}

export const clientConstant={
    GET_ALL_CLIENT_REQ:"GET_ALL_CLIENT_REQ",
    GET_ALL_CLIENT_SUC:"GET_ALL_CLIENT_SUC",
    GET_ALL_CLIENT_FAILURE:"GET_ALL_CLIENT_FAILURE",
    ADD_CLIENT_REQ:"ADD_CLIENT_REQ",
    ADD_CLIENT_SUC:"ADD_CLIENT_SUC",
    ADD_CLIENT_FAILURE:"ADD_CLIENT_FAILURE"
}

export const karigarConstant={
    GET_ALL_KARIGAR_REQ:"GET_ALL_KARIGAR_REQ",
    GET_ALL_KARIGAR_SUC:"GET_ALL_KARIGAR_SUC",
    GET_ALL_KARIGAR_FAILURE:"GET_ALL_KARIGAR_FAILURE",
<<<<<<< HEAD
    NEW_KARIGAR_REQ:"NEW_KARIGAR_REQ",
    NEW_KARIGAR_SUC:"NEW_KARIGAR_SUC",
    NEW_KARIGAR_FAILURE:"NEW_KARIGAR_FAILURE"
=======
    ADD_KARIGAR_REQ:"ADD_KARIGAR_REQ",
    ADD_KARIGAR_SUC:"ADD_KARIGAR_SUC",
    ADD_KARIGAR_FAILURE:"ADD_KARIGAR_FAILURE"
}

export const categoryConstant={
    GET_ALL_CATEGORY_REQ:"GET_ALL_CATEGORY_REQ",
    GET_ALL_CATEGORY_SUC:"GET_ALL_CATEGORY_SUC",
    GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
    CATEGORY_ADD_REQ:"CATEGORY_ADD_REQ",
    CATEGORY_ADD_SUC:"CATEGORY_ADD_SUC",
    CATEGORY_ADD_FAILURE:"CATEGORY_ADD_FAILURE"
}

export const orderConfirmConstant={
    ORDER_SET_REQ:"ORDER_SET_REQ",
    ORDER_SET_SUC:"ORDER_SET_SUC",
    ORDER_SET_FAILURE:"ORDER_SET_FAILURE",
    ORDER_SET_EMPTY:"ORDER_SET_EMPTY",
>>>>>>> 7f538adfeae6b1671d9d63991ac918df90637682
}