export const orderConstant={
    GET_ALL_ORDER_REQ:"GET_ALL_ORDER_REQ",
    GET_ALL_ORDER_SUC:"GET_ALL_ORDER_SUC",
    GET_ALL_ORDER_FAILURE:"GET_ALL_ORDER_FAILURE",
    NEW_ORDER_REQ:"NEW_ORDER_REQ",
    NEW_ORDER_SUC:"NEW_ORDER_SUC",
    NEW_ORDER_FAILURE:"NEW_ORDER_FAILURE",
    NEW_ORDER_PDF_REQ:"NEW_ORDER_PDF_REQ",
    NEW_ORDER_PDF_SUC:"NEW_ORDER_PDF_SUC",
    NEW_ORDER_PDF_FAILURE:"NEW_ORDER_PDF_FAILURE",
    EDIT_ORDER_REQ:"EDIT_ORDER_REQ",
    EDIT_ORDER_SUC:"EDIT_ORDER_SUC",
    EDIT_ORDER_FAILURE:"EDIT_ORDER_FAILURE",
    REPEAT_ORDER_REQ:"REPEAT_ORDER_REQ",
    REPEAT_ORDER_SUC:"REPEAT_ORDER_SUC",
    REPEAT_ORDER_FAILURE:"REPEAT_ORDER_FAILURE",
    CHANGE_ORDER_STATUS_REQ:"CHANGE_ORDER_STATUS_REQ",
    CHANGE_ORDER_STATUS_SUC:"CHANGE_ORDER_STATUS_SUC",
    CHANGE_ORDER_STATUS_FAILURE:"CHANGE_ORDER_STATUS_FAILURE",
    SEND_REM_REQ:"SEND_REM_REQ",
    SEND_REM_SUC:"SEND_REM_SUC",
    SEND_REM_FAILURE:"SEND_REM_FAILURE",
}

export const userConstant={
    USER_LOGIN_REQ:"USER_LOGIN_REQ",
    USER_LOGIN_SUC:"USER_LOGIN_SUC",
    USER_LOGIN_FAILURE:"USER_LOGIN_FAILURE",
    // USER_REGISTER_REQ:"USER_REGISTER_REQ",
    // USER_REGISTER_SUC:"USER_REGISTER_SUC",
    // USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE",
    USER_LOGOUT_REQ:"USER_LOGOUT_REQ",
    USER_LOGOUT_SUC:"USER_LOGOUT_SUC",
    USER_LOGOUT_FAILURE:"USER_LOGOUT_FAILURE",
    USER_ONLINE_REQ:"USER_ONLINE_REQ",
    USER_ONLINE_SUC:"USER_ONLINE_SUC",
    USER_ONLINE_FAILURE:"USER_ONLINE_FAILURE",
    USER_OFFLINE_REQ:"USER_OFFLINE_REQ",
    USER_OFFLINE_SUC:"USER_OFFLINE_SUC",
    USER_OFFLINE_FAILURE:"USER_OFFLINE_FAILURE",
    EMPTY_REQ:"EMPTY_REQ",
    EMPTY_SUC:"EMPTY_SUC",
    EMPTY_FAILURE:"EMPTY_FAILURE",
    OTP_VERIFY_REQ:"OTP_VERIFY_REQ",
    OTP_VERIFY_SUC:"OTP_VERIFY_SUC",
    OTP_VERIFY_FAILURE:"OTP_VERIFY_FAILURE",
    FORGOT_OTP_REQ:"FORGOT_OTP_REQ",
    FORGOT_OTP_SUC:"FORGOT_OTP_SUC",
    FORGOT_OTP_FAILURE:"FORGOT_OTP_FAILURE",
    FORGOT_OTP_VERIFY_REQ:"FORGOT_OTP_VERIFY_REQ",
    FORGOT_OTP_VERIFY_SUC:"FORGOT_OTP_VERIFY_SUC",
    FORGOT_OTP_VERIFY_FAILURE:"FORGOT_OTP_VERIFY_FAILURE",
    PASSWORD_CHANGE_REQ:"PASSWORD_CHANGE_REQ",
    PASSWORD_CHANGE_SUC:"PASSWORD_CHANGE_SUC",
    PASSWORD_CHANGE_FAILURE:"PASSWORD_CHANGE_FAILURE",
}

export const clientConstant={
    GET_ALL_CLIENT_REQ:"GET_ALL_CLIENT_REQ",
    GET_ALL_CLIENT_SUC:"GET_ALL_CLIENT_SUC",
    GET_ALL_CLIENT_FAILURE:"GET_ALL_CLIENT_FAILURE",
    ADD_CLIENT_REQ:"ADD_CLIENT_REQ",
    ADD_CLIENT_SUC:"ADD_CLIENT_SUC",
    ADD_CLIENT_FAILURE:"ADD_CLIENT_FAILURE",
    ADD_CLIENT_CSV_REQ:"ADD_CLIENT_CSV_REQ",
    ADD_CLIENT_CSV_SUC:"ADD_CLIENT_CSV_SUC",
    ADD_CLIENT_CSV_FAILURE:"ADD_CLIENT_CSV_FAILURE"
}

export const adminClientConstant={
    GET_ADMIN_ALL_CLIENT_REQ:"GET_ADMIN_ALL_CLIENT_REQ",
    GET_ADMIN_ALL_CLIENT_SUC:"GET_ADMIN_ALL_CLIENT_SUC",
    GET_ADMIN_ALL_CLIENT_FAILURE:"GET_ADMIN_ALL_CLIENT_FAILURE",
    DELETE_ADMIN_CLIENT_REQ:"DELETE_ADMIN_CLIENT_REQ",
    DELETE_ADMIN_CLIENT_SUC:"DELETE_ADMIN_CLIENT_SUC",
    DELETE_ADMIN_CLIENT_FAILURE:"DELETE_ADMIN_CLIENT_FAILURE"
}

export const adminKarigarConstant={
    GET_ADMIN_ALL_KARIGAR_REQ:"GET_ADMIN_ALL_KARIGAR_REQ",
    GET_ADMIN_ALL_KARIGAR_SUC:"GET_ADMIN_ALL_KARIGAR_SUC",
    GET_ADMIN_ALL_KARIGAR_FAILURE:"GET_ADMIN_ALL_KARIGAR_FAILURE",
    DELETE_ADMIN_KARIGAR_REQ:"DELETE_ADMIN_KARIGAR_REQ",
    DELETE_ADMIN_KARIGAR_SUC:"DELETE_ADMIN_KARIGAR_SUC",
    DELETE_ADMIN_KARIGAR_FAILURE:"DELETE_ADMIN_KARIGAR_FAILURE"
}

export const adminUserConstant={
    USER_ADMIN_REGISTER_REQ:"USER_ADMIN_REGISTER_REQ",
    USER_ADMIN_REGISTER_SUC:"USER_ADMIN_REGISTER_SUC",
    USER_ADMIN_REGISTER_FAILURE:"USER_ADMIN_REGISTER_FAILURE",
    ADD_USER_CSV_REQ:"ADD_USER_CSV_REQ",
    ADD_USER_CSV_SUC:"ADD_USER_CSV_SUC",
    ADD_USER_CSV_FAILURE:"ADD_USER_CSV_FAILURE",
    GET_ADMIN_ALL_USER_REQ:"GET_ADMIN_ALL_USER_REQ",
    GET_ADMIN_ALL_USER_SUC:"GET_ADMIN_ALL_USER_SUC",
    GET_ADMIN_ALL_USER_FAILURE:"GET_ADMIN_ALL_USER_FAILURE",
    DELETE_ADMIN_USER_REQ:"DELETE_ADMIN_USER_REQ",
    DELETE_ADMIN_USER_SUC:"DELETE_ADMIN_USER_SUC",
    DELETE_ADMIN_USER_FAILURE:"DELETE_ADMIN_USER_FAILURE",
    ADMIN_USER_ACTIVATE_REQ:"ADMIN_USER_ACTIVATE_REQ",
    ADMIN_USER_ACTIVATE_SUC:"ADMIN_USER_ACTIVATE_SUC",
    ADMIN_USER_ACTIVATE_FAILURE:"ADMIN_USER_ACTIVATE_FAILURE",
    ADMIN_USER_DEACTIVATE_REQ:"ADMIN_USER_DEACTIVATE_REQ",
    ADMIN_USER_DEACTIVATE_SUC:"ADMIN_USER_DEACTIVATE_SUC",
    ADMIN_USER_DEACTIVATE_FAILURE:"ADMIN_USER_DEACTIVATE_FAILURE",
}

export const adminOrderConstant={
    GET_ADMIN_ALL_ORDER_REQ:"GET_ADMIN_ALL_ORDER_REQ",
    GET_ADMIN_ALL_ORDER_SUC:"GET_ADMIN_ALL_ORDER_SUC",
    GET_ADMIN_ALL_ORDER_FAILURE:"GET_ADMIN_ALL_ORDER_FAILURE"
}

export const karigarConstant={
    GET_ALL_KARIGAR_REQ:"GET_ALL_KARIGAR_REQ",
    GET_ALL_KARIGAR_SUC:"GET_ALL_KARIGAR_SUC",
    GET_ALL_KARIGAR_FAILURE:"GET_ALL_KARIGAR_FAILURE",
    ADD_KARIGAR_REQ:"ADD_KARIGAR_REQ",
    ADD_KARIGAR_SUC:"ADD_KARIGAR_SUC",
    ADD_KARIGAR_FAILURE:"ADD_KARIGAR_FAILURE",
    ADD_KARIGAR_CSV_REQ:"ADD_KARIGAR_CSV_REQ",
    ADD_KARIGAR_CSV_SUC:"ADD_KARIGAR_CSV_SUC",
    ADD_KARIGAR_CSV_FAILURE:"ADD_KARIGAR_CSV_FAILURE"
}

export const categoryConstant={
    GET_ALL_CATEGORY_REQ:"GET_ALL_CATEGORY_REQ",
    GET_ALL_CATEGORY_SUC:"GET_ALL_CATEGORY_SUC",
    GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
    CATEGORY_ADD_REQ:"CATEGORY_ADD_REQ",
    CATEGORY_ADD_SUC:"CATEGORY_ADD_SUC",
    CATEGORY_ADD_FAILURE:"CATEGORY_ADD_FAILURE"
}

export const orderConfirmConstant={
    ORDER_SET_REQ:"ORDER_SET_REQ",
    ORDER_SET_SUC:"ORDER_SET_SUC",
    ORDER_SET_FAILURE:"ORDER_SET_FAILURE",
    ORDER_SET_EMPTY:"ORDER_SET_EMPTY",
}

export const toastConstant={
    TOAST_SET_MSG:"TOAST_SET_MSG",
    TOAST_EMPTY_STATE:"TOAST_EMPTY_STATE",
}

export const adminConstant={
    ADMIN_LOGIN_REQ:"ADMIN_LOGIN_REQ",
    ADMIN_LOGIN_SUC:"ADMIN_LOGIN_SUC",
    ADMIN_LOGIN_FAILURE:"ADMIN_LOGIN_FAILURE",
    ADMIN_LOGOUT_REQ:"ADMIN_LOGOUT_REQ",
    ADMIN_LOGOUT_SUC:"ADMIN_LOGOUT_SUC",
    ADMIN_LOGOUT_FAILURE:"ADMIN_LOGOUT_FAILURE"
}
