export const orderConstant={
    GET_ALL_ORDER_REQ:"GET_ALL_ORDER_REQ",
    GET_ALL_ORDER_SUC:"GET_ALL_ORDER_SUC",
    GET_ALL_ORDER_FAILURE:"GET_ALL_ORDER_FAILURE",
    NEW_ORDER_REQ:"NEW_ORDER_REQ",
    NEW_ORDER_SUC:"NEW_ORDER_SUC",
    NEW_ORDER_FAILURE:"NEW_ORDER_FAILURE",
    NEW_ORDER_PDF_REQ:"NEW_ORDER_PDF_REQ",
    NEW_ORDER_PDF_SUC:"NEW_ORDER_PDF_SUC",
    NEW_ORDER_PDF_FAILURE:"NEW_ORDER_PDF_FAILURE",
    EDIT_ORDER_REQ:"EDIT_ORDER_REQ",
    EDIT_ORDER_SUC:"EDIT_ORDER_SUC",
    EDIT_ORDER_FAILURE:"EDIT_ORDER_FAILURE",
}

export const userConstant={
    USER_LOGIN_REQ:"USER_LOGIN_REQ",
    USER_LOGIN_SUC:"USER_LOGIN_SUC",
    USER_LOGIN_FAILURE:"USER_LOGIN_FAILURE",
    USER_REGISTER_REQ:"USER_REGISTER_REQ",
    USER_REGISTER_SUC:"USER_REGISTER_SUC",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE",
    USER_LOGOUT_REQ:"USER_LOGOUT_REQ",
    USER_LOGOUT_SUC:"USER_LOGOUT_SUC",
    USER_LOGOUT_FAILURE:"USER_LOGOUT_FAILURE"
}

export const clientConstant={
    GET_ALL_CLIENT_REQ:"GET_ALL_CLIENT_REQ",
    GET_ALL_CLIENT_SUC:"GET_ALL_CLIENT_SUC",
    GET_ALL_CLIENT_FAILURE:"GET_ALL_CLIENT_FAILURE",
    ADD_CLIENT_REQ:"ADD_CLIENT_REQ",
    ADD_CLIENT_SUC:"ADD_CLIENT_SUC",
    ADD_CLIENT_FAILURE:"ADD_CLIENT_FAILURE"
}

export const adminClientConstant={
    GET_ADMIN_ALL_CLIENT_REQ:"GET_ADMIN_ALL_CLIENT_REQ",
    GET_ADMIN_ALL_CLIENT_SUC:"GET_ADMIN_ALL_CLIENT_SUC",
    GET_ADMIN_ALL_CLIENT_FAILURE:"GET_ADMIN_ALL_CLIENT_FAILURE"
}

export const adminKarigarConstant={
    GET_ADMIN_ALL_KARIGAR_REQ:"GET_ADMIN_ALL_KARIGAR_REQ",
    GET_ADMIN_ALL_KARIGAR_SUC:"GET_ADMIN_ALL_KARIGAR_SUC",
    GET_ADMIN_ALL_KARIGAR_FAILURE:"GET_ADMIN_ALL_KARIGAR_FAILURE"
}

export const adminUserConstant={
    GET_ADMIN_ALL_USER_REQ:"GET_ADMIN_ALL_USER_REQ",
    GET_ADMIN_ALL_USER_SUC:"GET_ADMIN_ALL_USER_SUC",
    GET_ADMIN_ALL_USER_FAILURE:"GET_ADMIN_ALL_USER_FAILURE"
}

export const adminOrderConstant={
    GET_ADMIN_ALL_ORDER_REQ:"GET_ADMIN_ALL_ORDER_REQ",
    GET_ADMIN_ALL_ORDER_SUC:"GET_ADMIN_ALL_ORDER_SUC",
    GET_ADMIN_ALL_ORDER_FAILURE:"GET_ADMIN_ALL_ORDER_FAILURE"
}

export const karigarConstant={
    GET_ALL_KARIGAR_REQ:"GET_ALL_KARIGAR_REQ",
    GET_ALL_KARIGAR_SUC:"GET_ALL_KARIGAR_SUC",
    GET_ALL_KARIGAR_FAILURE:"GET_ALL_KARIGAR_FAILURE",
    ADD_KARIGAR_REQ:"ADD_KARIGAR_REQ",
    ADD_KARIGAR_SUC:"ADD_KARIGAR_SUC",
    ADD_KARIGAR_FAILURE:"ADD_KARIGAR_FAILURE"
}

export const categoryConstant={
    GET_ALL_CATEGORY_REQ:"GET_ALL_CATEGORY_REQ",
    GET_ALL_CATEGORY_SUC:"GET_ALL_CATEGORY_SUC",
    GET_ALL_CATEGORY_FAILURE:"GET_ALL_CATEGORY_FAILURE",
    CATEGORY_ADD_REQ:"CATEGORY_ADD_REQ",
    CATEGORY_ADD_SUC:"CATEGORY_ADD_SUC",
    CATEGORY_ADD_FAILURE:"CATEGORY_ADD_FAILURE"
}

export const orderConfirmConstant={
    ORDER_SET_REQ:"ORDER_SET_REQ",
    ORDER_SET_SUC:"ORDER_SET_SUC",
    ORDER_SET_FAILURE:"ORDER_SET_FAILURE",
    ORDER_SET_EMPTY:"ORDER_SET_EMPTY",
}

export const toastConstant={
    TOAST_SET_MSG:"TOAST_SET_MSG",
    TOAST_EMPTY_STATE:"TOAST_EMPTY_STATE",
}

export const adminConstant={
    ADMIN_LOGIN_REQ:"ADMIN_LOGIN_REQ",
    ADMIN_LOGIN_SUC:"ADMIN_LOGIN_SUC",
    ADMIN_LOGIN_FAILURE:"ADMIN_LOGIN_FAILURE",
    ADMIN_LOGOUT_REQ:"ADMIN_LOGOUT_REQ",
    ADMIN_LOGOUT_SUC:"ADMIN_LOGOUT_SUC",
    ADMIN_LOGOUT_FAILURE:"ADMIN_LOGOUT_FAILURE"
}
